options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
substitutions:
  _SERVICE: 'skinlesionclassificationdermai'
  _REGION: 'us-central1'

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE/$_SERVICE:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image to Artifact Registry'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE/$_SERVICE:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', '$_SERVICE',
    '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE/$_SERVICE:latest',
    '--platform', 'managed',
    '--region', '$_REGION',
    '--allow-unauthenticated'
  ]
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE/$_SERVICE:latest'
